name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Her 12 saatte bir Ã§alÄ±ÅŸÄ±r
  workflow_dispatch: # Manuel tetikleme

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub Stats Card
        uses: Platane/snk@v3
        id: stats
        with:
          github_user_name: ${{ github.repository_owner }}
          
      - name: Generate Stats SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ramazan-yildirim
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Istanbul
          filename: images/github-metrics.svg
          
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "ðŸ“Š GitHub istatistikleri gÃ¼ncellendi" && git push)
